### ISSUE TITLE
Option parseDate doesn't seem to work

### ISSUE THREAD

**Issue by ohtanya** [haoxins/react-flatpickr#101]
https://codesandbox.io/embed/react-example-7yoo1

It looks like formatDate works but parseDate never gets called. Am I doing something wrong?

**Comment by ohtanya** [comment]
@jacobmischka Yes actually I've been able to narrow it down to react-flatpickr being the issue, because it does work with flatpickr alone. I even tried several different versions of flatpickr. Here it is working in flatpickr 4.6.2.
https://codepen.io/wryk/pen/pozEMyB?editors=1111

**Comment by jacobmischka** [comment]
Ah, I think it's because you're giving it a Date object already, so it's not parsing anything.

This example seems to work, please let me know if I'm missing something. https://codesandbox.io/embed/react-example-v96y6

**Comment by ohtanya** [comment]
@jacobmischka that was it! Thank you so much.
