### ISSUE TITLE
defaultDate is not working

### ISSUE THREAD

**Issue by j-avila** [haoxins/react-flatpickr#103]
I'm trying to set a default date to an range flatpickr but doesn't work in any way

my code is :
let today = new Date()
let defaultDate = ["30-10-2019", today]
<Flatpickr
              value={this.state.date}
              placeholder= {translate('select_placeholder')}
              options={
                {
                  mode: 'range',
                  dateFormat: "d-M-Y",
                  "locale": Spanish,
                  defaultDate: defaultDate
                }
              }
              onChange={date => { this.props.setDate(date)}}
            />

**Comment by jacobmischka** [comment]
Yeah, if you give it a `value` the default is not going to do anything. Instead just set `this.state.date` equal to what you want the default to be.

**Comment by j-avila** [comment]
work like a charm,  thanks!
