### ISSUE TITLE
How do I clear the date in flatpickr ?

### ISSUE THREAD

**Issue by jessicagury** [haoxins/react-flatpickr#105]
Hi! 

I would like to add a button to clear the date in react-flatpickr.
I found this example on the flatpicker.js.org website: https://flatpickr.js.org/examples/#flatpickr-external-elements but I failed to find how to apply it with the react wrapper.

Does anyone know how I could make it work?

**Comment by jacobmischka** [comment]
You should be able to access the flatpickr instance from the wrapper via the `flatpickr` property, like so: https://codesandbox.io/embed/react-example-ioopi

Alternatively, you should just be able to set the value to `null` instead, that should work fine too.

**Comment by jessicagury** [comment]
Thank you @jacobmischka for the example.
It works well!
