### ISSUE TITLE
Props documentation

### ISSUE THREAD

**Issue by sigfriedCub1990** [haoxins/react-flatpickr#115]
Recently I've found this library because a co-worker will use it for an internal project we're working on, so far this was the only library that gave him enough flexibility to do what he wanted to do but, that being said I think that apart from the `flatpickr` documentation we should have a document with some examples and a reference of the `components's`props.
I'll gladly do this if you think it's worth it.

**Comment by jacobmischka** [comment]
It would be much appreciated! If you submit a PR I'll look it over as soon as possible, thanks!

**Comment by sigfriedCub1990** [comment]
https://github.com/haoxins/react-flatpickr/pull/116#issue-364462899

**Comment by jacobmischka** [comment]
Closed in #116, thanks again!
