### ISSUE TITLE
How to show year selection?

### ISSUE THREAD

**Issue by RylkovAlex** [haoxins/react-flatpickr#117]
When I use react-flatpickr component I'cant select year in the calendar, like it was in simple flatpickr instance.

I have this:
![image](https://user-images.githubusercontent.com/32511612/72984220-3349a380-3df4-11ea-96f6-728510a872c8.png)

But I want this:
![image](https://user-images.githubusercontent.com/32511612/72984284-62601500-3df4-11ea-93f4-bc1158bc8272.png)

Please explain to me how to show the year selection? 
Thanks!

**Comment by zahari00** [comment]
I had the same problem, but I saw that the input is there, but it's just not visible. So adding "display: flex;" to ".flatpickr-current-month" fixed it for me.
![image](https://user-images.githubusercontent.com/40611132/75343182-92418300-58a0-11ea-8663-908f2627770f.png)

**Comment by jacobmischka** [comment]
Pretty sure this was an upstream flatpickr issue that has since been resolved. Closing this now because it's quite old.

**Comment by spvn** [comment]
I'm having this exact same problem now more than a year after this issue was closed... no idea why this is happening...
