### ISSUE TITLE
this.flatpickr.setDate is not a function

### ISSUE THREAD

**Issue by sahilpaudel-pe** [haoxins/react-flatpickr#118]
I am getting this message on the console if i add options attribute to the Flatpickr component.

TypeError
this.flatpickr.setDate is not a function
DateTimePicker.componentDidMount

[https://codesandbox.io/s/semantic-ui-example-dfv6u](url)  for reproducing the error.

**Comment by jacobmischka** [comment]
Interesting, looks like `componentDidMount` is never being called.

**Comment by jacobmischka** [comment]
It seems the problem is centered around the `render` prop, when I remove it it seems to work. I'll have to look deeper later.

**Comment by sahilpaudel-pe** [comment]
> It seems the problem is centered around the `render` prop, when I remove it it seems to work. I'll have to look deeper later.

Yes, please I need that render prop.

Thanks.

**Comment by jacobmischka** [comment]
Okay, the problem was twofold:

1. React Semantic UI doesn't actually apply the `ref` prop to the dom element, so you need to do a little workaround.
2. This package previously didn't handle changing dom elements, which it should now as of `3.10.0`.

So, here's how you can make your example work after updating `react-flatpickr` to `~3.10.0`:

```js
  const CustomInput = ({ value, defaultValue, inputRef, ...props }) => {
    return <Input {...props} defaultValue={defaultValue} ref={ref => {
      if (ref && ref.inputRef && ref.inputRef.current) {

        inputRef(ref.inputRef.current);
      }
    }} />;
  };
```

**Comment by sahilpaudel-pe** [comment]
https://codesandbox.io/s/react-flatpickr-3g1ph

I tried doing same but still getting the same error.

**Comment by jacobmischka** [comment]
Your config is invalid, the property you want is `dateFormat` not `formatDate`.

https://codesandbox.io/s/react-flatpickr-lqzjx
