### ISSUE TITLE
Disabled prop not getting updated on mobile

### ISSUE THREAD

**Issue by SamuelTrew** [haoxins/react-flatpickr#125]
I have a checkbox and a flatpickr component such that when I check the checkbox the flatpickr should become selectable.

This works fine when I am on desktop but as soon as I switch to mobile it stops working. I have to force a reload of the parent component to the Example component below. 
I know the component that is wrapping around the checkbox and flatpickr is getting updated properly as console logging is showing the necessary values getting printed.

Example:

```
const Example = observer(({ checked }) => {
   console.log('1')
   console.log(checked)

   return (
      <Flatpickr
         disabled={!checked}
         options={{ maxDate: new Date() }}
      />
   )
})
```

**Comment by SamuelTrew** [comment]
There is a 'solution' for any of those who are currently stuck by it.
Add a key prop that is variable.

I had something like 
`key={filter + '  ' + checked}` 
and this worked just as I knew it would always lead to a unique key (based on my filter variable).

However, I don't think causing a complete remount of the component should be necessary

**Comment by jacobmischka** [comment]
I believe it's because `disabled` is not a reactive property, it's being passed to the input element and apparently causing issues. You should use one of the [Flatpickr options](https://flatpickr.js.org/options/) (probably `clickOpens`) to enable/disable the picker.

**Comment by SamuelTrew** [comment]
But why would it work fine on web then?

**Comment by jacobmischka** [comment]
Who knows
