### ISSUE TITLE
3.10.5 throws "Maximum update depth exceeded" error

### ISSUE THREAD

**Issue by Josh865** [haoxins/react-flatpickr#131]
There seems to be an error in 3.10.5 that causes a "Maximum update depth exceeded" error, even in the most basic use case. Here's an example: https://codesandbox.io/s/practical-voice-odzwj?file=/src/App.js.

Downgrading to 3.10.4 fixed the issue, so it appears to be caused by a change in 3.10.5.

**Comment by jacobmischka** [comment]
You're right. Sorry about that, the `3.10.5` changes have been reverted and `3.10.4` has been rereleased as `3.10.6`.
