### ISSUE TITLE
Update how flatpickr is brought into react-flatpickr to help prevent breaking changes

### ISSUE THREAD

**Issue by romans12** [haoxins/react-flatpickr#134]
This library pulls in the latest changes to flatpickr by grabbing the latest minor & patch fixes. This works as intended as long as the library adheres to semantic versioning. 

Would it be possible to switch the library to only grab the current version? There have been two instances in the last year where flatpickr has released breaking changes and we are not able to use an earlier version because of how the library is currently bringing in this dependency.

**Comment by jacobmischka** [comment]
I don't think I fully understand the request, but if you want to override the version resolution you can use something like yarn's `resolutions` field: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
