### ISSUE TITLE
Bug: Open calendar programmatically stopped working

### ISSUE THREAD

**Issue by mahcr** [haoxins/react-flatpickr#135]
Using a ref to open the calendar is no longer working. It looks like the class name is not being added to the div. 

![react-flatpickr-error](https://user-images.githubusercontent.com/16544451/92526463-c9470880-f1e2-11ea-8d40-d897b37319a2.gif)

react-flatpickr version: 3.10.6
flatpickr version: 4.6.6

Live example: 
https://stackblitz.com/edit/react-flatpickr-example-not-working

**Comment by husseyexplores** [comment]
The flatpickr library is preventing the widget to open for these reasons:
https://github.com/flatpickr/flatpickr/issues/399#issuecomment-260007013

You can do something like this. Read the comments there:
https://stackblitz.com/edit/react-flatpickr-example-not-working-ncxoms

Or, you may also wrap the `open` method in the `setTimeout` like this:
```js
const openCalendar = () => {
  setTimeout(() => calendarRef.current.flatpickr.open(), 0);
}
```
I personally don't like the `setTimeout` hack.

**Comment by jacobmischka** [comment]
Upstream issue, as mentioned above.
