### ISSUE TITLE
#unable to use flatpicker as a child component.

### ISSUE THREAD

**Issue by ishu202** [haoxins/react-flatpickr#137]
### react-flatpickr wont render when imported from a child element.

I have been trying to use the react-flatpickr inside a child component and every time it tries to render. 
It expects the option arguments from the parent to render. after providing a prop from parent it complains about the props need to be an array. even after passing the array. this is the structure in which it shows the options in the react code inspector.

**here is a screen shot check it out.**

![A860966B-3217-4091-AEC8-C31729CC9678_4_5005_c](https://user-images.githubusercontent.com/73513328/98458311-c9b53e80-2154-11eb-8a94-51111aa83bb0.jpeg)

**here is the screenshot.**

**Comment by jacobmischka** [comment]
Please provide a code sample if you would like this investigated.

**Comment by ishu202** [comment]
here is the commit point check it out.
https://github.com/ishu202/calenderwidget/commit/260c51ae92c2a2a725d936bc093be96be4bdf033

**Comment by impulsivetomato** [comment]
@ishu202 add a codesandbox example
