### ISSUE TITLE
unable to clear flatpickr selected date on click of cross icon

### ISSUE THREAD

**Issue by sankita15** [haoxins/react-flatpickr#141]
I am trying to use clear functionality which is available in flatpickr, but facing issue when i am using it in react-flatpickr. 
My use case is very simple where I have added an svg cross icon and on click of that icon I want to clear the selected date in the flatpickr input field.

```js
const element = document.querySelector("[class=flatpickr-input]")

<>
<img src={calendar} alt="calendar" className={'flat-calendar'} data-testid={'flat-calendar-icon'}/>
    <Flatpickr options={config} value={value && new Date(value)} onChange={(eventValue) => localOnChange(eventValue[0])}/>
<img src={crossFilled} alt="calendar" className={'clear-icon'} onClick={() => element.clear()}/>
<>
```

I am not sure if I am using it wrong or something I am missing, if anyone can help it would be great.
Thanks in advance !!

**Comment by jacobmischka** [comment]
Don't manually dig around in the dom to clear input elements, this is going to break the component's state.

In your `onClick` handler clear `value`, and change your `value=` prop for the `Flatpickr` component to pass along the null, or something like that.
