### ISSUE TITLE
onChange() execute twice when use render with ref in react-flatpickr

### ISSUE THREAD

**Issue by QiaoLi1996** [haoxins/react-flatpickr#144]
When I tried to use render with ref in react-flatpickr, outer component onChange execute twice, but inner Component onChange no trigger. This seems unreasonable。

What I want to  is that use react-flatpickr combine with material-ui TextField，now I have a problem. After selecting the date, because there is only trigger outer flatpickr- onChange twice and no trigger inner TextField-onChange, the TextField UI render
not
And then I Change material-ui TextField to common input, it still exist. This Problem has troubled me for a long time，so I had to ask for help. 

I already create the codesandbox, here is the Link:
https://codesandbox.io/s/mystifying-faraday-7xd4s

## Environment

* react-flatpickr version used: 3.10.6
* Browser name and version: Chrome
* OS and version:Windows 10

**Comment by jacobmischka** [comment]
I think this is an issue with the CssTextField events, not necessarily this component. Try changing the inner event to `onInput` and uncommenting the `value` prop definition: https://codesandbox.io/s/youthful-elion-p05j1

```js
import * as React from "react";
import "./styles.css";
import FlatPicker from "react-flatpickr";
import { TextField as MTextField, withStyles, Button } from "@material-ui/core";
import "flatpickr/dist/themes/material_green.css";

const CssTextField = withStyles({
  root: {
    "& input:invalid ~ fieldset": {
      borderColor: "red"
    }
  }
})(MTextField);

export default function App() {
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>

      <FlatPicker
        data-enable-time
        options={{ minDate: "2021-01-05", allowInput: true }}
        onChange={(data) => {
          console.log("1----" + data);
        }}
        render={(innerprops, ref) => {
          return (
            <CssTextField
              label="test"
              variant="outlined"
              helperText="It seems have a problem"
              value={innerprops.value}
              defaultValue={innerprops.defaultValue}
              onInput={(e) => {
                console.log("2----" + e);
              }} // onChange={() => innerprops.onChange }
              inputRef={ref}
            />
          );
        }}
      />

      <FlatPicker
        data-enable-time
        options={{ minDate: "2021-01-05", allowInput: true }}
        onChange={(data) => {
          console.log("3----" + data);
        }}
        render={({ defaultValue, value, ...props }, ref) => {
          return (
            <input
              defaultValue={defaultValue}
              onChange={(e) => {
                console.log("4----" + e);
              }}
              ref={ref}
            />
          );
        }}
      />
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/3939997/108985818-187cda80-7657-11eb-8ca2-3a58f0250348.png)

**Comment by jacobmischka** [comment]
I'm going to assume this is the solution you were looking for, if not write back and I can reopen.
