### ISSUE TITLE
react-flatpickr cause the transpilation error on IE11

### ISSUE THREAD

**Issue by kwdowik** [haoxins/react-flatpickr#147]
I've updated `react-flatpickr` from `3.7.1` to `3.10.6` and start to receive transpilation error related to `getDaysInMonth` method in the output bundle file on IE11

**Transpilation error**
![image](https://user-images.githubusercontent.com/23464934/106873128-6ba4e280-66d4-11eb-9bf9-f46bcf900ba5.png)

**getDaysInMonth**
![image](https://user-images.githubusercontent.com/23464934/106873057-56c84f00-66d4-11eb-8187-630767fac027.png)

After a bit of debugging, turned out that the upgrade from version 3.10.2 to 3.10.4 actually cause the error and to be more precise `flatpickr` package that has been updated  from `4.6.6` to `4.6.9` (screenshot below)

![image](https://user-images.githubusercontent.com/23464934/106871862-000e4580-66d3-11eb-9817-16b4059a74af.png)

**Comment by jacobmischka** [comment]
This is a bundling issue, IE11 does not support [method definitions syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions). You'll need to configure babel to [compile the syntax away](https://babeljs.io/docs/en/babel-plugin-transform-shorthand-properties) if you want to support IE11, probably using [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env).
