### ISSUE TITLE
onClose is triggered right after onOpen on certain cases

### ISSUE THREAD

**Issue by ml-devninja** [haoxins/react-flatpickr#148]
Assumptions:
flatpickr ver: `3.10.5+`
react ver: any
input focus: off/none

Steps to reproduce:

Go to: https://codesandbox.io/s/react-flatpickr-demo-with-cra-forked-dw4b8?fontsize=14&hidenavigation=1&theme=dark

When focus is off put cursor on very bottom border of input and click
![image](https://user-images.githubusercontent.com/15577330/108957674-31df5000-7672-11eb-8006-168263f4681b.png)

Now flatpickr will be shown and immediately hide after - both `onOpen` and `onClose` events are triggered

If you'll downgrade to `3.10.4` issue is not there so it's introduced in `3.10.5` according to my little investigation

**Comment by jacobmischka** [comment]
Sorry, I'm not able to reproduce using your link. Please provide more detailed instructions if I'm missing something.

![Peek 2021-02-24 03-01](https://user-images.githubusercontent.com/3939997/108975914-9a1b3b00-764c-11eb-9a6f-1672759be6d5.gif)

**Comment by ml-devninja** [comment]
Yes - sorry - there's 3.10.4

please change version (on left side) to 3.10.5

![image](https://user-images.githubusercontent.com/15577330/108976517-e33cb080-7687-11eb-8e08-0384b044c0aa.png)

**Comment by jacobmischka** [comment]
Oh, yes. The commit that caused that issue was reverted in the 3.10.6 release. Please upgrade.

![image](https://user-images.githubusercontent.com/3939997/108978315-157dec00-764f-11eb-8095-dafee11c4fe8.png)

**Comment by jacobmischka** [comment]
Though for what it's worth, I'm not able to reproduce it on 3.10.5 either. :shrug:

**Comment by jacobmischka** [comment]
Oh, just kidding, I am able to, but only in Chrome, not Firefox. Strange, because there shouldn't be any difference between 3.10.4 and 3.10.6:

![image](https://user-images.githubusercontent.com/3939997/108979357-3135c200-7650-11eb-968a-c902323455dc.png)

Not really sure what to do.

**Comment by ml-devninja** [comment]
Its present in `3.10.6` - so i had to downgrade to `3.10.4` in my app

**Comment by jacobmischka** [comment]
The most annoying part is I'm not able to reproduce locally (using the included example in this repo), only using that codesandbox. I think there was a problem with deploying the 3.10.6 release, it looks like the changes didn't get reflected for some reason? I pushed a 3.10.7 release after changing nothing except package.json, and I'm no longer able to reproduce in codesandbox. Can you try that?

**Comment by ml-devninja** [comment]
Looks like `3.10.7` is free of this bug ;)

Thanks for super-quick reaction! 💪 

closing

**Comment by jacobmischka** [comment]
Neat, weird how finnicky it was. Thanks for posting about the issue.

**Comment by sgehrman** [comment]
I'm seeing this in the latest version.  My dialog is getting closed by flatpickr somehow.  I have to click right below the date string.
