### ISSUE TITLE
react-flatpickr gives build time error

### ISSUE THREAD

**Issue by sashiksu** [haoxins/react-flatpickr#149]
When using react-flatpickr in react project, it gives a build error in build time.
![image](https://user-images.githubusercontent.com/20171631/112319543-2fedc880-8cd4-11eb-9d4b-ba92dfbe7168.png)

Even tried in lower versions and got this error. 
Anyone has faced this issue?

**Comment by jacobmischka** [comment]
As you can see in the path, that's a base `flatpickr` file, not something in this wrapper component. I have not run into this myself, sorry.

**Comment by sashiksu** [comment]
I got this error in react 16.2 version. 
Lately, I tried "react-flatpickr" in the new version of react 17.0.2 and there wasn't that error. 
Probably it's some type script not supporting or compatible issue with package.
