### ISSUE TITLE
OnChange does not fire in time only picker when toggling AM/PM on the keyboard

### ISSUE THREAD

**Issue by DrMavenRebe** [haoxins/react-flatpickr#150]
I've got code that looks like this:

```
    <Flatpickr
        options={{
            enableTime: true,
            noCalendar: true,
            altFormat: "G:i K",
            altInput: true,
            altInputClass: "",
            dateFormat: "H:i:S"
        }}
        onChange={ (selection, string) => handleChange(i, string, "arrival") }
        value={ stop.arrival }
        placeholder="Select Time..."
        className="pa3 w-10"
    />
```

The onChange fires when when you set the time via keyboard and it fires when you click the AM or PM with a mouse but using the keyboard to change the AM and PM does not fire the onChange hook. Obviously, this is causing some fun bugs. Has anyone else seen this? Anyone know a workaround?

**Comment by jacobmischka** [comment]
I think this is an upstream flatpickr issue: https://github.com/flatpickr/flatpickr/issues/2224

**Comment by DrMavenRebe** [comment]
Confirmed. Using the `onValueUpdate` worked for us.
