### ISSUE TITLE
restrict user to select two dates on onChange with mode:range

### ISSUE THREAD

**Issue by ahsanshah7865** [haoxins/react-flatpickr#152]
I have the following configurations for displaying react-flatpickr. 

I have a simple daterangepicker with defaultDates, what i want to achieve is that whenever user wants to change the date, we restrict the user to select two dates from calender, 
right now what's happening is, as we have already provided start and end date. when user select any date the onChange handler only change one particular date and close the calender.

````
<Flatpickr
                id="roundTripDates"
                type="text"
                options={{
                    mode: 'range',
                    dateFormat: "j",
                    minDate: "today",
                    showMonths: 2,
                    shorthandCurrentMonth: true,
                    defaultDate: [new Date(), new Date("+5days")],
                    plugins: [rangePlugin({ input: "#roundTripDates-to" })],
                    onChange: (selected: any) => {

                    }
                }}
            />

**Comment by jacobmischka** [comment]
This is an issue/question for the upstream flatpickr rangePlugin. It behaves the same way on the [plugins demo page](https://flatpickr.js.org/plugins/), so it has nothing to do with react-flatpickr.

**Comment by ahsanshah7865** [comment]
Thanks for the insight @jacobmischka
