### ISSUE TITLE
t.flatpickr.destroy is not a function. (In 't.flatpickr.destroy()', 't.flatpickr.destroy' is undefined)',

### ISSUE THREAD

**Issue by olegstan** [haoxins/react-flatpickr#166]
Hello. 
On some devices I got this error.  
t.flatpickr.destroy is not a function. (In 't.flatpickr.destroy()', 't.flatpickr.destroy' is undefined)',
Fix please.

**Comment by jacobmischka** [comment]
You'll have to provide literally any information if you want any support with this. Better yet, pull requests welcome. Closing this until proper reproduction information is provided.
