### ISSUE TITLE
Time Selector is missing

### ISSUE THREAD

**Issue by iamabhishek00** [haoxins/react-flatpickr#171]
I am trying to implement a dropdown to select both Date and Time, but the time dropdown is missing (Screenshot Attached)

```
<Col className="mb-1" md="6" sm="12">
        <Label for='date-time-picker'>Date & Time</Label>
        <Flatpickr
            value={picker}
            data-enable-time
            id='date-time-picker'
            className='form-control'
            onChange={date => setPicker(date)}
        />
</Col>
```
![Screenshot-20211112161438-1033x652](https://user-images.githubusercontent.com/92790592/141454547-e181483c-02d1-482b-b976-e0eee0a5045b.png)

`"react-flatpickr": "3.9.1"`

I am not sure if this is a bug or some error from my end.

**Comment by jacobmischka** [comment]
`data-` properties won't work on the `<Flatpickr />` component, please use the [config option](https://flatpickr.js.org/options/) instead:

```js
<Flatpickr
            value={picker}
            options={{
              enableTime: true
            }}
            id='date-time-picker'
            className='form-control'
            onChange={date => setPicker(date)}
        />
```

**Comment by iamabhishek00** [comment]
Thanks for the response @jacobmischka.

As suggested, I tried to use the config option, but still can't get the time dropdown. 

Just out of curiosity, why do `data-` properties won't work on the `<Flatpickr />` component?
Because I read [here](https://github.com/haoxins/react-flatpickr#usage), where `data-enable-time` is used in `<Flatpickr />` component.

**Comment by jacobmischka** [comment]
Sorry ha, you're absolutely right, I just totally blanked about that feature. Sorry, I didn't get a lot of sleep last night.

Your code should be working fine, so I'm not sure what's going wrong: https://codesandbox.io/s/funny-shaw-bsjg4?file=/src/App.js

![image](https://user-images.githubusercontent.com/3939997/141526113-f7f86d55-2d38-47b8-bcf5-e9134cc83d33.png)

Can you check the DOM inspector to see if the `.flatpickr-time` element exists?

![image](https://user-images.githubusercontent.com/3939997/141526182-acdf9d14-80ad-487e-b834-662129b03555.png)

I wonder if you just have some styling issues going on?

**Comment by hanswang0608** [comment]
Setting options prop like this worked for me:
`<Flatpickr
        options={{ enableTime: true }}
/>`
