### ISSUE TITLE
Bug: Picker in 'range' mode clears selection in the input field when clicking out of picker

### ISSUE THREAD

**Issue by mpetkov** [haoxins/react-flatpickr#173]
Steps to reproduce:

1. Go to this sandbox: https://codesandbox.io/s/react-flatpickr-forked-t802bn?file=/index.js:111-115
2. Click on the range picker.
3. Click out of the picker without selecting any dates.
4. The input will be cleared even though in the console it says the the onChange kept the original date.

**Comment by jacobmischka** [comment]
I'm unable to reproduce using your link above, but even if I were I'm pretty sure this would be an upstream issue.

Also, your example has a lot of issues. Your initialized date is a single date, but you're using `range` mode which returns an array of dates, and you're not changing the `value` in the `onChange` handler which means things are instantly going to be out of sync.

**Comment by mpetkov** [comment]
I update the link to fix the "lot of issues" you described. As you are aware of how react works, it obviously didn't make any difference to the results.

Please let me know what browser and machine you tried it on. I just tried it again on Windows using latest Chrome and can reproduce the issue 100% of the time. If you follow the steps exactly as outline, you will be able to reproduce.

**Comment by mpetkov** [comment]
Also just to be clear, I tried using flatpickr directly and it works fine. So issue only appears when using the react-flatpickr version.

**Comment by jacobmischka** [comment]
Maybe you mean after you select only one item and don't complete the range? It wasn't really clear that that's what you meant. In any case, that behaves the same for me with vanilla flatpickr?

Firefox:

https://user-images.githubusercontent.com/3939997/167649570-733ddced-5f50-4491-982b-39bf8cd9d394.mp4

Chrome:

https://user-images.githubusercontent.com/3939997/167650295-d00f6327-9c69-4093-8760-39e3bd587b24.mp4

Vanilla Flatpickr:

https://user-images.githubusercontent.com/3939997/167650280-6213dc77-8bcf-4f51-b00a-de9cbcea12b8.mp4

**Comment by jacobmischka** [comment]
This is not a bug in this library, it's how `allowInput: true` behaves. Please raise an issue in upstream flatpickr if you feel this is a bug.

https://codesandbox.io/s/mystifying-saha-7dwb2k?file=/src/index.js
