### ISSUE TITLE
Unable to set date, if it's value less then today's

### ISSUE THREAD

**Issue by parish-shrestha** [haoxins/react-flatpickr#174]
Hey, This issue is fixed in the jquery flatpickr. I've attached the link to the issue down below.
Tried to implement the same idea in this package, but it didn't work.
How can we fix this issue in this react one as well?

[https://github.com/flatpickr/flatpickr/issues/760](https://github.com/flatpickr/flatpickr/issues/760)

**Comment by es-roshanb** [comment]
I am having the same issue, Any answer related to this.

**Comment by jacobmischka** [comment]
Same workarounds as upstream.

**Comment by es-roshanb** [comment]
this was the solution in upstream
`onReady: function(){
        if (this.parseDate(your_date_string) < this.parseDate("today")) {
           this._input.value = your_date_string;
           alert("oh, the date you selected etc..");
       }`
But I got 

> TypeError: Cannot read properties of undefined (reading 'parseDate')

I guess this is undefined, how can I get around with this?

**Comment by jacobmischka** [comment]
The third argument to the callback is the flatpickr instance, use that instead of `this`.

https://flatpickr.js.org/events/

**Comment by es-roshanb** [comment]
Hello @jacobmischka thanks for your time, I also tried that, to set with the instance still not working, My whole component and options
` <Flatpickr
                                className="form-control flatpickr-date deadline-picker"
                                options={options}
                                id={'deadline_'+row.id}
                                disabled={!row.is_editable}
                                defaultValue={row.deadline?row.deadline:"today"}
                                // defaultValue={setDeadlineDefault(row)}
                                onChange={([deadline]) => {
                                    handleDateChange(deadline,row);
                                }}
                                onReady={(date,dateStr,instance) => {
                                        instance._input.value=dateStr;
                                        
                                }}
                            />`
                            
and my options for datepicker is
`const options = {
                        enableTime: false,
                        dateFormat: "Y-m-d",
                        minDate: "today"
                      };`.
