### ISSUE TITLE
onChange not working flatpickr 4.6.10

### ISSUE THREAD

**Issue by Levelsncurves** [haoxins/react-flatpickr#180]

**Comment by Levelsncurves** [comment]
onChange not working flatpickr 4.6.10

**Comment by jacobmischka** [comment]
Yeah it is: https://codesandbox.io/s/sad-sutherland-08psny?file=/src/App.js

**Comment by jacobmischka** [comment]
Oh, you mean the hook in `options`. You should really be clearer if you want your issues to be taken seriously.

**Comment by jacobmischka** [comment]
They're actually both working individually, turns out they just clobber each other. Though this has nothing to do with flatpickr 4.6.10, so I don't think this is even what you meant.

**Comment by Levelsncurves** [comment]
> Yeah it is: https://codesandbox.io/s/sad-sutherland-08psny?file=/src/App.js

https://codesandbox.io/s/bold-http-wbrtly

how handle month changes not working

**Comment by jacobmischka** [comment]
Upstream issue: https://github.com/flatpickr/flatpickr/issues/2651

**Comment by jacobmischka** [comment]
Workaround is mentioned in that issue. Either pin the flatpickr dependency to a different working version, wait for a flatpickr update, or use the workaround.
