### ISSUE TITLE
Versions > 3.10.4 seem to break when using multiple flatpickrs on the same page

### ISSUE THREAD

**Issue by TurtleTony** [haoxins/react-flatpickr#181]
I noticed some weird behaviour after upgrading from 3.10.4 to 3.10.7. After a while of debugging it turns out that (sometimes, usually after 2-3 clicks) changing a flatpickr date triggers the onChange hooks of ALL flatpickrs on the page. This also seems to happen with onClose as well as other hooks. Code looked something like this:

```
let [from, setFrom] = useState<Date>(new Date());
let [to, setTo] = useState<Date>(new Date());
...
<Flatpickr
  data-enable-time
  value={from}
  onChange={(date) => {
    setFrom(date[0] as Date);
    }}
/>

<Flatpickr
  data-enable-time
  value={to}
  onChange={(date) => {
    setTo(date[0] as Date);
    }}
/>
```

After changing both inputs once, they would become interlocked and always both change. Very weird

EDIT: Just to make this clear, pinning the version back to 3.10.4 fixed the issue immediately.

**Comment by jacobmischka** [comment]
Sorry, I'm not able to reproduce: https://codesandbox.io/s/zealous-cache-s3r3cn?file=/src/App.js

Can you try to reproduce in codesandbox and post a link?

**Comment by TurtleTony** [comment]
I can, good suggestion! https://codesandbox.io/s/trusting-banzai-xg7rym

It appears more is required to produce said odd behaviour. In my version I have a shared options object defining format, minDate and a few other things. The issue appears now, but I can't make sense of it.

Thank you for looking into this btw, greatly appreciated!

**Comment by jacobmischka** [comment]
Should be fixed in `3.10.9`, thanks for the report! https://codesandbox.io/s/reverent-ride-x4qb4n

**Comment by x3igh7** [comment]
Hey @jacobmischka I have a similar issue with a slightly different setup in 3.10.9, not clear what is going on.

https://codesandbox.io/s/magical-cohen-ldzf4x

**Comment by jacobmischka** [comment]
No, your `onChange` handlers just aren't right.

https://codesandbox.io/s/infallible-butterfly-9ituzg

**Comment by x3igh7** [comment]
Okay, do you have any idea why I have to do it that way? I've admittedly not been using React long but I've never seen this issue before?

**Comment by jacobmischka** [comment]
The callback is basically just caching it, use the function form instead https://stackoverflow.com/a/59990838
