### ISSUE TITLE
[semver] Breaking change in patch release

### ISSUE THREAD

**Issue by rcocks-hl** [haoxins/react-flatpickr#184]
Commit 4dec90acbe9e96c30cc152a76cee5e83d173f5a8 introduced a breaking change for some projects, a dependency on React 17+.

This broke semver guarantees, and now `npm update` breaks when run in a project with React 16.x and react-flatpickr 3.10.7 installed.

Please bump at least the minor release numbers when making breaking changes so the package version can be set with to, for example, 3.10.x for React 16 projects.

**Comment by jacobmischka** [comment]
You're right, I'm sorry about that, it was a mistake to bump the version when changing to `peerDependencies`. `3.10.10` should fix that by broadening the acceptable range.

Thanks for the issue!
