### ISSUE TITLE
Bug: does not update the value for onChange

### ISSUE THREAD

**Issue by bobmazy** [haoxins/react-flatpickr#186]
Steps to reproduce:

1. Go to this sandbox: https://codesandbox.io/s/react-flatpickr-not-changing-onchange-j823j0
2. Insert a value for the `begin` date picker
3. Insert a value for the `end` date picker
4. The value from the date selection for the begin is removed. A `console.log()` shows that the value of the `filter` state is not updated in this function and the `begin` value is still undefined, even though we previously changed the `begin` value.

It seems that React-Flatpickr saves the initialization value for `onChange` and then does not update it.
This still process worked in version `3.10.7` .

**Comment by jacobmischka** [comment]
Same issue as https://github.com/haoxins/react-flatpickr/issues/181#issuecomment-1081112178, your setState handlers aren't right. Use the callback form.

**Comment by joakimjm** [comment]
I think it's premature to close this and the similar, related issues. 

I'm experiencing the same issue with stale closures using this Flatpickr component, and I can't do what you suggest with `setState(old => ...)`. I have to rely on the uni-directional dataflow to work when calling onChange. The consequence of it not working is that the stale closures of Flatpickr cause out of sync state to be passed back up to the component tree.

Replacing the Flatpickr components with regular input fields solve the data flow issue, so I'm unable to use the library in until its current state, unless you know other workarounds?

**Comment by jacobmischka** [comment]
I believe it was a bug that it ever worked before, we were unnecessarily adding new handlers on every render. You are supposed to use the callback form if state updates depend on previous state values.

**Comment by joakimjm** [comment]
I've refactored my component tree to pass down change handlers in the same style as you suggest, and it does seem to work, so thanks for being persistent about it 😅 

It makes sense that you don't want to keep recreating handlers on every render. Is that an optimization you've made or does it fix something specific, like a memory leak integrating with flatpickr library?

**Comment by jacobmischka** [comment]
It was found/fixed when fixing a related bug during hook merging, before we were accidentally overwriting the hooks specified in `options` with the component-level hooks (`onChange` etc). Oops!
