### ISSUE TITLE
On mobile browser, it don`t turns the date input into a native input

### ISSUE THREAD

**Issue by poslavsky** [haoxins/react-flatpickr#36]
First of all, thanks for your work!
We use react-flatpickr on our site(minskgo.by). And have a problem.
On iPhone react-flatpickr work very bad. We don`t see native input (like here https://chmln.github.io/flatpickr/mobile-support/).
Is it possible to solve this problem?

**Comment by wasabigeek** [comment]
@poslavsky did you use any non-supported functionality like enable/disable of dates? If you do Flatpickr itself will not display the native pickers (as pointed out in the [link](https://chmln.github.io/flatpickr/mobile-support/) you shared)
