### ISSUE TITLE
property 'classname' does not exist on type 'intrinsicattributes & intrinsicclassattributes

### ISSUE THREAD

**Issue by balakrishna511** [haoxins/react-flatpickr#81]
Hi,
Am using Flatpickr  in react JS with **Typescript** i have the below issue when i add the className property to the component.
<Flatpickr className='form-control clickable' ref="refDatePicker" options={this.state.options} value={this.state.selectValue} onChange={this.setDate} />
this issue is occurred when i have added the className property to the component.

Can anyone please help us on how to resolve .

**Comment by jacobmischka** [comment]
Apologies, I'm not very familiar with TypeScript (though I really should be at this point). I imagine you need to pull/create/update a type definition from https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by jacobmischka** [comment]
https://www.npmjs.com/package/@types/react-flatpickr
