### ISSUE TITLE
hide the flatpickr 

### ISSUE THREAD

**Issue by akshayaj29** [haoxins/react-flatpickr#82]

**Comment by akshayaj29** [comment]
Can we hide flatpickr for  specific condition ?

**Comment by jacobmischka** [comment]
Sorry, can you be more specific?

If you're looking to programmatically close the calendar, you should be able to do something like this using [flatpickr's `close` method](https://flatpickr.js.org/instance-methods-properties-elements/#close):

```js
<div>
    <Flatpickr ref={this.fp} />
    <button type="button" onClick={() => { this.fp.flatpickr.close(); }}>Close</button>
</div>
```
