### ISSUE TITLE
Using 'locale' togerther with 'firstDayOfWeek'

### ISSUE THREAD

**Issue by Kafty** [haoxins/react-flatpickr#87]
Hey :) I found out I need to use locale together with the firstDayOfWeek.. And I can't figure out how to specify it in the options prop. Can you help me please ? Thanks :)

**Comment by jacobmischka** [comment]
Does this in the options object not work? https://flatpickr.js.org/localization/

```js
{
    locale: {
        firstDayOfWeek: 2
    }
}
```

**Comment by Kafty** [comment]
this works perfectly fine, but I would like to do something like this:
{
    locale: l10n.sk,
    locale: {
        firstDayOfWeek: 2
    }
}

and I didn't find the way to do that. If that would be possible, would be great

**Comment by jacobmischka** [comment]
Locales are just objects, so using a spread or `Object.assign` should work to override the default for the locale:

```js
{
    locale: {
        ...l10n.sk,
        firstDayOfWeek: 2
    }
}
```

**Comment by Kafty** [comment]
that's fantastic ! Thanks so much 👍
