### ISSUE TITLE
Month is suddenly a dropdown, and year is suddenly an input

### ISSUE THREAD

**Issue by ohtanya** [haoxins/react-flatpickr#94]
Is there any way to disable this from happening? Month and year used to be static and now month has become a dropdown and year is an input. 

This started happening today, and I don't see any releases in the past 26 days, otherwise I would just use an older version.

**Comment by jacobmischka** [comment]
Because you're looking in the wrong library! https://github.com/flatpickr/flatpickr/releases

Locking flatpickr in your project to whatever version you like should work, if you don't like the new release.
