### ISSUE TITLE
unstable display behavior of the current month

### ISSUE THREAD

**Issue by mg901** [haoxins/react-flatpickr#96]
```
export const DateTimePicker = () => {
  const [date, setDate] = useState(new Date());
  useStyles();

  return (
    <Flatpickr
      data-enable-time
      value={date}
      options={{
        prevArrow: "*",
        nextArrow: "*",
        // mode: "range",
        time_24hr: true,
        dateFormat: "d.m.Y H:i",
        locale: Russian
      }}
      onChange={() => {
        setDate(date);
      }}
    />
  );
};
```

I connect `react-flatpickr 3.9.0`  to [codesandbox](https://codesandbox.io/s/condescending-burnell-5tqul), and month information is displayed in the span tag (expected beh
avior).

<img width="336" alt="Screenshot 2019-06-25 at 14 45 55" src="https://user-images.githubusercontent.com/7874664/60095760-ff23dc80-9757-11e9-9dea-8be39220d1b1.png">

<img width="308" alt="Screenshot 2019-06-25 at 14 41 34" src="https://user-images.githubusercontent.com/7874664/60095688-cf74d480-9757-11e9-9bfc-b90384b8c0d2.png">

However, if I transfer this code to a [local project](https://github.com/mg901/date-time-picker) (based on the Create React App), the month is displayed as a list. 

<img width="341" alt="Screenshot 2019-06-25 at 14 47 16" src="https://user-images.githubusercontent.com/7874664/60095815-2bd7f400-9758-11e9-9fdd-0c28a4500ed4.png">

<img width="661" alt="Screenshot 2019-06-25 at 14 48 53" src="https://user-images.githubusercontent.com/7874664/60096324-51193200-9759-11e9-97e7-093398fc348c.png">

Which of the component's behaviors is correct? Can you set options to control the display of the month (month name or list of months)?

**Comment by jacobmischka** [comment]
I believe the difference is due to the version of `flatpickr` (not `react-flatpickr`) being used in each project. 

[Looks like the select-based version was released in flatpickr 4.6.0](https://github.com/flatpickr/flatpickr/releases/tag/v4.6.0), feel free to lock the version used in your project to whichever version you like by running `npm install flatpickr@<4.6.0`, for example.

Closing because I don't think this is a related to this wrapper component in particular, but feel free to write back.

**Comment by mg901** [comment]
@jacobmischka Probably you did not understand me correctly. in the local project and on codesandbox, exactly the same code and the same dependencies with the same versions are used. It is strange to see this behavior of the same code.

**Comment by jacobmischka** [comment]
I believe I did. While your version of `react-flatpickr` may have been the same, I am betting that your version of `flatpickr` itself was not. As a nested dependency, without manually locking it to a specific version or using a lockfile its version can change.

This library (react-flatpickr) has `flatpickr@^4.5.7` as a dependency. Thus, versions of the underlying flatpickr library may change without changing the version of react-flatpickr.

**Comment by mg901** [comment]
the problem is solved by one line, if you use yarn
```
  "resolutions": {
    "react-flatpickr/flatpickr": "4.5.7"
  }
```
