### ISSUE TITLE
Value is empty when manually entering the time and using an AltInput

### ISSUE THREAD

**Issue by Thomas-Negrault** [haoxins/react-flatpickr#97]
I made a simple code using the one on the Readme to illustrate the error:

![Peek 2019-07-01 10-57](https://user-images.githubusercontent.com/6841201/60423994-a50b9700-9bef-11e9-902b-8186164517ee.gif)

As you can see, the real input value update when the datepicker is closed (click outside) but if I manually enter the time, the value is `""`
Code used:
```
import React, {Component} from 'react';
import './App.css';
import 'flatpickr/dist/themes/material_green.css';
import Flatpickr from 'react-flatpickr';

export default class App extends Component {
  constructor() {
    super();

    this.state = {
      date: new Date(),
    };
  }

  render() {
    const {date} = this.state;
    return (
        <Flatpickr
            data-enable-time
            name="realInput"
            value={date}
            options={{
              altInput: true,
              altInputClass: 'altInput',
            }}
            onChange={date => { this.setState({date}); }}/>
    );
  }
}
```

**Comment by andrewkusuma** [comment]
anyone how to fix this? when I try using onClose seems same just send empty string ""

**Comment by Guferos** [comment]
I had the same problem and the way to fix it was to change the `minuteIncrement` option to `1`:
```
<Flatpickr
            ...
            options={{
              minuteIncrement: 1
            }}
            ...
/>
```

`minuteIncrement` is set to 5 by default and when you change the time manually to something that cannot divide by 5 it fails a validation somewhere and date comes empty.

**Comment by jacobmischka** [comment]
Oh neat, thanks for getting to the bottom of this.

I suppose you could also do something weird like supply a `parseDate` option function that rounds to the nearest 5, but setting the increment makes a lot more sense.

I'm going to close this now, but feel free to keep discussing.
